version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "py"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
    # Ignore karena cuma ada di workflow runtime
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
